#!/bin/bash

for p in 0.4 0.45 0.46 0.47 0.48; do
    for traces in 10 20 40 60 80 100 200 400 600; do
        mkdir -p "res_soft/t0_known_d01/${p}_${traces}"
        for traceset in $(seq 0 1 9); do
            python3 -u ./examples/w0_attack.py -l 3 --t0-known -n $traces -p $p -i 50 -d 0.1 -s $traceset > "res_soft/t0_known_d01/${p}_${traces}/${traceset}.out"
        done 
    done
done